# Generated by Django 5.0.1 on 2024-01-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sanpham_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
