# Generated by Django 5.0.1 on 2024-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_donhang_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachhang',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
