# Generated by Django 5.0.1 on 2024-01-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_phone_number_khachhang_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khachhang',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='lastname',
        ),
    ]
