# Generated by Django 5.0.1 on 2024-01-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_giohang_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ten_dm', to='app.danhmuc')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='category',
            field=models.ManyToManyField(related_name='sanpham', to='app.danhmuc'),
        ),
    ]
